### ISSUE TITLE
US1 - Como analista de estoque, eu quero cadastrar novos produtos, para complementar meu estoque.

### ISSUE THREAD

**Issue by felipealiel** [LuannaBenezar/Backlog-Produto-Sprint#1]
Critérios de aceitação: 
Os usuários podem cadastrar apenas 1 produto por vez. 
Os usuários não deverão cadastrar o mesmo produto mais de 1 vez, mesmo que mude as datas de entrada.

**Comment by Marcosgabrielpeixoto** [comment]
# ID - 1
## O requisito não permite registrar mais de 1 produto por vez, sendo que em um fardo de arroz são composto por 30 pacotes de 1 quilograma e assim o estoquista não poderá cadastrar os 30 de uma só vez.

**Comment by Marcosgabrielpeixoto** [comment]
# ID - 2
## Por critério de aceitação não poderá adicionar vários produtos por lote.
